# SAM CLI deployment configuration
# Run `sam deploy --guided` to generate with your specific values

version = 0.1

[default.deploy.parameters]
stack_name = "pitch-world"
resolve_s3 = true
s3_prefix = "pitch-world"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false

[default.build.parameters]
cached = true
parallel = true
